### PR TITLE
Job labels

### LINKED ISSUE #176: Readable job ids
More human readable info for jobs (in phase view). Also, sort jobs to display the newest at the top of the dropdown list.

Add label that should be shown instead of auto-generated id.

### LINKED ISSUE #180: wrong new Location upload folder
when creating an operation and creating a new location, the location entity is uploaded to "ForecastDS/FoR-Data" instead of "ForecastDS/FoR-Data/Locations"

### LINKED ISSUE #181: wrong config file upload folder
when creating an operation and uploading a new config file, the config entity is uploaded to "ForecastDS/FoR-Data" instead of "ForecastDS/FoR-Data/Configs"

### PR DESCRIPTION
**Pull request by soofstad**
- Label for jobs (set date time on creation)
- More icons on buttons
- New Locations and Configs uses separate sub packages.

closes #181 closes #180 closes #176

### CODE REVIEW

File: web/custom-plugins/forecast-of-response/src/Pages/OperationCreate.tsx [hunk 1]
```diff
@@ -137,11 +138,25 @@ const onClickCreate = (
   const getIds = []
   // Prepare the uncontained entities for the Operation
   operationLocation.type = Blueprints.LOCATION
-  getIds.push(getEntityId(operationLocation, token, isNewEntity.location))
+  getIds.push(
+    getEntityId(
+      operationLocation,
+      token,
+      isNewEntity.location,
+      'FoR-Data/Locations'
```
Comment (KristianKjerstad) [inline web/custom-plugins/forecast-of-response/src/Pages/OperationCreate.tsx:146]: maybe add new variables to const.ts with values for "'FoR-Data/Locations'" and 'FoR-Data/Configs'?

**Review by KristianKjerstad — APPROVED** [review]

File: web/custom-plugins/forecast-of-response/src/Pages/OperationCreate.tsx (hunk 1 above)
Comment (soofstad) [reply web/custom-plugins/forecast-of-response/src/Pages/OperationCreate.tsx]: Fixed
