### PR TITLE
update operator phase view and fix bug for phase view

### LINKED ISSUE #177: Test operator user can display results correctly

### PR DESCRIPTION
**Pull request by KristianKjerstad**
update the view for the operator

* also, for the result compoent, reset the plot when selected result changes

closes #177 

image

### CODE REVIEW

**Review by soofstad — CHANGES_REQUESTED** [review]
Operators should not be able to select simConfig.
Also, there should only be one Published SimConf at any time.

File: web/custom-plugins/forecast-of-response/src/Types.ts [hunk 1]
```diff
@@ -55,6 +55,11 @@ export type StringMap = {
   [key: string]: string
 }
 
+export type TResultReference = {
```
Comment (soofstad) [inline web/custom-plugins/forecast-of-response/src/Types.ts:58]: This could be renamed to "TReference"

**Review by soofstad — CHANGES_REQUESTED** [review]
Operator should not be able to select "Result". Always show latest

**Review by soofstad — APPROVED** [review]
